remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
title: Mar1us So Blog
description: feedId:63808905908834304+userId:56898394898846720
author: Mar1us
